# fly.toml app configuration file generated for snowgoose on 2025-03-29T13:56:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snowgoose'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile"
  target = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
